---
title: Voer een Scratch-project uit in de modus Volledig scherm
hero_image: images/banner.png
description: Switch in and out of full-screen mode in Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - 
    title: Voer een Scratch-project uit in de modus Volledig scherm
