title: Run a Scratch project in full-screen mode
hero_image: images/banner.png
description: Switch in and out of the full screen view in Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - title: Run a Scratch project in full-screen mode
