title: scratch3-full-screen
hero_image: images/banner.png
description: scratch3-full-screen description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
