---
title: Run a Scratch project in full-screen mode
hero_image: प्रतिमा / banner.png
description: Switch in and out of full-screen mode in Scratch
version: 0
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - 
    title: Run a Scratch project in full-screen mode
