---
title: Iprojekthi yakho igcwalise iskrini xa uyidlalayo
hero_image: images/banner.png
description: Tshintsha-tshintsha phakathi kweskrini esincinci nesi gcweleyo
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - title: Iprojekthi yakho igcwalise iskrini xa uyidlalayo
