---
title: フルスクリーンモードでスクラッチ・プロジェクトを実行する
hero_image: images/banner.png
description: Switch in and out of full-screen mode in Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - 
    title: フルスクリーンモードでスクラッチ・プロジェクトを実行します。
