---
title: Pokreni Scratch projekt u punom zaslonu
hero_image: images/banner.png
description: Uključivanje i isključivanje iz načina punog zaslona u Scratchu
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - title: Pokreni Scratch projekt u punom zaslonu
