---
title: Rhedeg prosiect Scratch yn y modd sgrin lawn
hero_image: images/banner.png
description: Newid i mewn ac allan o'r modd sgrin lawn yn Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - title: Rhedeg prosiect Scratch yn y modd sgrin lawn
