---
title: Ausführen eines Scratch-Projekts im Vollbildmodus
hero_image: images/banner.png
description: Ein- und Ausschalten des Vollbildmodus in Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - title: Ausführen eines Scratch-Projekts im Vollbildmodus
