---
title: Execute um projeto Scratch em modo de tela cheia
hero_image: images/banner.png
description: Entre e saia do modo visualização em tela cheia no Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - title: Execute um projeto Scratch em modo de tela cheia
