---
title: Spusťte projekt Scratch v režimu celé obrazovky
hero_image: images/banner.png
description: Zapněte a vypněte režim celé obrazovky v aplikaci Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - title: Spusťte projekt Scratch v režimu celé obrazovky
