---
title: Ejecuta un proyecto de Scratch en modo de pantalla completa
hero_image: images/banner.png
description: Cambia entre pantalla normal y pantalla completa en Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - 
    title: Ejecuta un proyecto de Scratch en modo de pantalla completa
