---
title: Uruchom projekt Scratch w trybie pełnoekranowym
hero_image: images/banner.png
description: Włączanie i wyłączanie trybu pełnoekranowego w Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - title: Uruchom projekt Scratch w trybie pełnoekranowym
