---
title: Kör ett Scratch-projekt i helskärmsläge
hero_image: images/banner.png
description: Växla in i och ut ur helskärmsläge i Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - title: Kör ett Scratch-projekt i helskärmsläge
