---
title: Exécuter un projet Scratch en mode plein écran
hero_image: images/banner.png
description: Basculer dans et hors de la vue plein écran dans Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - title: Exécuter un projet Scratch en mode plein écran
