---
title: Esegui un progetto Scratch in modalità a schermo intero
hero_image: images/banner.png
description: Attiva e disattiva la modalità a schermo intero in Scratch
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - 
    title: Esegui un progetto Scratch in modalità a schermo intero
